### ISSUE TITLE
CarryOn client crash when connecting to server 1.20.6 [Fabric]

### ISSUE THREAD

**Issue by PlaidBonsai8922** [Tschipp/CarryOn#656]
### Expected Behavior
Join server with CarryOn mod normally

### Actual Behavior
Connection lost error - lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (carryon:sync_scripts)

### Steps to Reproduce
Install CarryOn version 2.1.4 on Minecraft 1.20.6 and on server running the same Minecraft version

### Version of Minecraft, Carry On, Forge/Fabric
Fabric

### Screenshots encouraged
![image](https://github.com/user-attachments/assets/9ad37e74-3e8c-4d54-8d0f-0e30aad53ef1)
![image](https://github.com/user-attachments/assets/695816ef-0563-4f05-9739-9bd2dc324b7c)

**Comment by Vrylex** [comment]
i have the same problem but for 1.21

**Comment by kalevaz** [comment]
same on 1.21

**Comment by CoNtrolV1** [comment]
same, in 1.21...

**Comment by PlaidBonsai8922** [comment]
> same, in 1.21...

> same on 1.21

> i have the same problem but for 1.21

It is fixed for 1.21 in the 2.2.1 update of the mod

**Comment by xvhone** [comment]
Hey I tried downloading both the same version which is 2.1.4 on the server and on my client and still the same issue
