### ISSUE TITLE
Settings spontaneously revert to the default when using the config screen.

### ISSUE THREAD

**Issue by Estecka** [Tschipp/CarryOn#746]
Continuation of my comment in #733.

Making any change in the config screen can cause some settings to be reverted to their default values. I've observed this on tile-blacklist, entity-blacklist, and tile-whitelist. Presumably, all list-type settings are affected.

There are three phenomenons at play here:
- After changing any setting on the screen, **all** settings are written to the config file.
- Upon opening the config screen, it always shows the default values for list-type settings, instead of showing the active settings.
- Changes to list-type settings don't take effect until the game is restarted.

### Repro:
1. Before starting the game. Open the config file in a text editor, and remove `minecraft:armor_stand` from the entity blacklist.
2. Start the game, and confirm that you are able to pick-up armor stands.
    - (Optional) In the config screen, observe that armor stands are listed in the entity blacklist
3. In the config screen, change an unrelated settings, e.g, increase `maxDistance`.
   - (Optional) After closing the config screen, reopen the config file: Observe that armor stands are again listed in the entity blacklist.
4. Restart the game: You are no longer able to pick-up armor stands.

### Versions:
Minecraft 1.21.4
Carry-On 2.3.0
Cloth Config 17.0.144
Fabric Loader 0.16.10
Fabric API 0.115.1

**Comment by Tschipp** [comment]
Fixed in next release, thanks for the useful repro steps

**Comment by Estecka** [comment]
Can confirm it's all fixed. 👍 
I think you forgot to increment the patch version number though.
