### ISSUE TITLE
Broken donation link

### ISSUE THREAD

**Issue by martinkadlec0** [Tschipp/CarryOn#778]
Hey, I wanted to send a little appreciation money to you as this has been my favorite mod for a long time, but it seems the donation link on Modrinth is not working:
https://www.paypal.com/donate?token=jaMlIr7HelT01_RNkn3xCnTWXMwo_eDtziLIAJkH8PJMb5tbVkqEDZCx4xM4DzL_gapvzg56IWbeY3xH&fromUL=true&country.x=CH&locale.x=en_US

It says "Something's not right. This page doesn't exist.".

**Comment by Lunascaped** [comment]
Check his website

**Comment by Tschipp** [comment]
Thanks for letting me know! I've fixed it, here is a working link: https://www.paypal.com/donate?token=oWPpwl_NfU2IcTpY-r2ofvmgJMoIpgRzxXsEAjaOZ_M9x86yCtCiBKSZJZnkzhwC_TrY1OoPLz3YU-Mm&locale.x=US

Also, thank you for considering to donate :)

**Comment by martinkadlec0** [comment]
@Tschipp still doesn't seem to be working :( 

![Image](https://github.com/user-attachments/assets/989d0716-929d-47c2-a55b-e4666d7856f6)
